-- CREATE TABLE Customer22 (
--     customer_id INT PRIMARY KEY,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     email VARCHAR(100) UNIQUE,
--     phone VARCHAR(15),
--     address VARCHAR(255),
--     city VARCHAR(50),
--     state VARCHAR(50),
--     zip_code VARCHAR(10),
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- INSERT INTO Customer22 
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES 
-- (1, 'Swarna', 'Gowri', 'swarna@example.com', '9876543210', 
--  '12 MG Road', 'Bangalore', 'Karnataka', '560001');
-- INSERT INTO CUSTOMER22 
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (2, 'Rahul', 'Sharma', 'rahul@example.com', '9123456780', 
--  '45 Brigade Road', 'Bangalore', 'Karnataka', '560025');

-- SELECT * from CUSTOMER22;
-- INSERT INTO Customer22 
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (4, 'Arjun', 'Mehta', 'arjun.mehta@example.com', '9012345678',
--  '101 MG Road', 'Chennai', 'Tamil Nadu', '600001');
-- INSERT INTO Customer22
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (5, 'Priya', 'Nair', 'priya.nair@example.com', '9345678901',
--  '22 Lake View', 'Kochi', 'Kerala', '682001');
-- INSERT INTO CUSTOMER22
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (6, 'Vikram', 'Singh', 'vikram.singh@example.com', '9871234560',
--  '55 Civil Lines', 'Delhi', 'Delhi', '110001');
-- INSERT INTO Customer22
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (7, 'Neha', 'Patel', 'neha.patel@example.com', '9765432109',
--  '88 Ring Road', 'Ahmedabad', 'Gujarat', '380001');
-- INSERT INTO Customer22
-- (customer_id, first_name, last_name, email, phone, address, city, state, zip_code)
-- VALUES
-- (8, 'Rohit', 'Kumar', 'rohit.kumar@example.com', '9654321098',
--  '14 Sector 17', 'Chandigarh', 'Chandigarh', '160017');   
SELECT * FROM CUSTOMER22 ;
 