CREATE TABLE TABLE1(id1 NUMBER);
INSERT INTO TABLE1 (id1) VALUES (1);
INSERT INTO TABLE1 (id1) VALUES (2);
INSERT INTO TABLE1 (id1) VALUES (3);
INSERT INTO TABLE1 (id1) VALUES (4);

CREATE TABLE TABLE2 (id2 NUMBER);
INSERT INTO TABLE2 (id2) VALUES (1);
INSERT INTO TABLE2 (id2) VALUES (2);
INSERT INTO TABLE2 (id2) VALUES (5);


SELECT * FROM TABLE1;

SELECT * FROM TABLE2;
-- inner joint
SELECT * from TABLE1 join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

SELECT * from TABLE1 INNER join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

SELECT count(*) from TABLE1 INNER join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

-- left joint
SELECT * from TABLE1 LEFT join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

SELECT count(*) from TABLE1 LEFT join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

-- right joint
SELECT * from TABLE1 RIGHT join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

SELECT count(*) from TABLE1 RIGHT join TABLE2 on TABLE1.ID1 = TABLE2.ID2;
-- full joint
SELECT * from TABLE1 FULL join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

SELECT count(*) from TABLE1 FULL join TABLE2 on TABLE1.ID1 = TABLE2.ID2;

-- cross joint
SELECT * from TABLE1 CROSS join TABLE2 ;

SELECT count(*) from TABLE1 CROSS join TABLE2 ;

