CREATE TABLE employee5(
    emp_id NUMBER,
    emp_name VARCHAR(15)
);

INSERT into EMPLOYEE5 (EMP_ID,EMP_NAME) VALUES (1,'swarna');

INSERT into EMPLOYEE5 (EMP_ID,EMP_NAME) VALUES (2,'gowri');

INSERT into EMPLOYEE5 (EMP_ID,EMP_NAME) VALUES (3,'bhanu');

INSERT into EMPLOYEE5 (EMP_ID,EMP_NAME) VALUES (4,'hema');

INSERT into EMPLOYEE5 (EMP_ID,EMP_NAME) VALUES (5,'sree');

SELECT * from EMPLOYEE5;

CREATE TABLE emp_salary(
    emp_id NUMBER,
   emp_salary NUMBER (10,2)
);
INSERT into EMP_SALARY (EMP_ID,EMP_SALARY) VALUES (1,10000);

INSERT into EMP_SALARY (EMP_ID,EMP_SALARY) VALUES(2,50000);

INSERT into EMP_SALARY (EMP_ID,EMP_SALARY) VALUES (3,80000);

INSERT into EMP_SALARY (EMP_ID,EMP_SALARY) VALUES  (5,90000);

-- display emp_id , emp_name amd salary from emp database

SELECT * from EMPLOYEE5 full join EMP_SALARY on EMPLOYEE5.EMP_ID = EMP_SALARY.EMP_ID;

SELECT * from EMPLOYEE5 LEFT join EMP_SALARY on EMPLOYEE5.EMP_ID = EMP_SALARY.EMP_ID;

SELECT EMPLOYEE5.EMP_ID , EMPLOYEE5.EMP_NAME, EMP_SALARY.EMP_SALARY from EMPLOYEE5
 LEFT join EMP_SALARY on EMPLOYEE5.EMP_ID = EMP_SALARY.EMP_ID;

SELECT ed.EMP_ID , ed.EMP_NAME, es.EMP_SALARY from EMPLOYEE5 ed
 LEFT join EMP_SALARY  es on ed.EMP_ID = es.EMP_ID;

 -- inner joint
 SELECT ed.EMP_ID , ed.EMP_NAME, es.EMP_SALARY from EMPLOYEE5 ed
 INNER join EMP_SALARY  es on ed.EMP_ID = es.EMP_ID;

 -- right
 SELECT ed.EMP_ID , ed.EMP_NAME, es.EMP_SALARY from EMPLOYEE5 ed
 RIGHT join EMP_SALARY  es on ed.EMP_ID = es.EMP_ID;

 





