-- CREATE TABLE Employees (
--     id INT PRIMARY KEY,
--     name VARCHAR(100),
--     city VARCHAR(100),
--     department VARCHAR(100),
--     salary DECIMAL(10,2)
-- );
-- INSERT INTO EMPLOYEES (id, name, city, department,SALARY )
-- VALUES
-- (1,'Rahul', 'hyderabad','IT',10000);
-- INSERT INTO EMPLOYEES (id, name, city, department,SALARY )
-- VALUES
-- (2, 'Bhanu', 'Bangalore', 'IT', 55000);
-- INSERT INTO EMPLOYEES (id, name, city, department,SALARY )
-- VALUES
-- (3, 'Anita', 'Hyderabad', 'HR', 45000);
-- INSERT INTO EMPLOYEES (id, name, city, department,SALARY )
-- VALUES
-- (4, 'Kiran', 'Chennai', 'Finance', 60000);
-- INSERT INTO EMPLOYEES (id, name, city, department,SALARY )
-- VALUES
-- (5, 'Sneha', 'Mumbai', 'Marketing', 50000);
-- SELECT * FROM EMPLOYEES;
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (6, 'Arjun', 'Delhi', 'IT', 65000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
--  (7, 'Priya', 'Bangalore', 'HR', 48000);
--  INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (8, 'Vikram', 'Pune', 'Finance', 72000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (9, 'Meera', 'Kolkata', 'Marketing', 53000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (10, 'Rohit', 'Hyderabad', 'IT', 61000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (11, 'Divya', 'Chennai', 'HR', 47000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (12, 'Sanjay', 'Mumbai', 'Finance', 75000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (13, 'Neha', 'Delhi', 'Marketing', 52000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (14, 'Aman', 'Pune', 'IT', 68000);
-- INSERT INTO Employees (id, name, city, department, salary) VALUES
-- (15, 'Kavya', 'Bangalore', 'Finance', 70000);
-- SELECT * FROM EMPLOYEES;
-- SELECT id ,name from EMPLOYEES;
-- SELECT id as emp_id , city from EMPLOYEES;
-- SELECT * from EMPLOYEES where DEPARTMENT = 'IT';
-- SELECT * from EMPLOYEES;
-- SELECT * from EMPLOYEES order by SALARY ASC; 
-- SELECT * from EMPLOYEES ORDER by SALARY DESC;
-- SELECT DISTINCT DEPARTMENT FROM EMPLOYEES;
-- SELECT COUNT(*) FROM EMPLOYEES;
-- SELECT min(salary) FROM EMPLOYEES;
-- SELECT MAX(salary) FROM EMPLOYEES;
-- SELECT AVG(salary) FROM EMPLOYEES;
-- SELECT * FROM EMPLOYEES ;
--SELECT sum(SALARY) from EMPLOYEES WHERE DEPARTMENT = 'IT';
 
-- SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT = 'IT';
-- select count(*) from EMPLOYEES where salary >5000;
-- select count(*) from EMPLOYEES where salary < 5000;
-- SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY BETWEEN 50000 AND 70000;
-- SELECT DEPARTMENT , SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT ;
 --SELECT DEPARTMENT , AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT;