-- CREATE TABLE Orders ( Order_ID INT PRIMARY KEY,
--  Order_Date DATE,
-- Customer_ID VARCHAR(10),
-- Customer_Name VARCHAR(100), 
-- Product_Category VARCHAR(100), 
-- Product_Name VARCHAR(150), 
-- Quantity INT, 
-- Unit_Price DECIMAL(10,2), 
-- Payment_Mode VARCHAR(50), 
-- Store_Location VARCHAR(100)
--  ); 
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1001, '01-02-2026', 'C001', 'Ravi Kumar', 'Electronics', 'Wireless Mouse', 2, 799, 'UPI', 'Bangalore');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1002, '02-02-2026', 'C002', 'Sneha Reddy', 'Grocery', 'Basmati Rice 5kg', 1, 650, 'Credit Card', 'Hyderabad');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1003, '03-02-2026', 'C003', 'Arjun Mehta', 'Fashion', 'Men''s T-Shirt', 3, 499, 'Cash', 'Chennai');

-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1004, '04-02-2026', 'C004', 'Priya Sharma', 'Electronics', 'Bluetooth Speaker', 1, 1499, 'Debit Card', 'Mumbai');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1005, '05-02-2026', 'C005', 'Kiran Rao', 'Home  Kitchen', 'Mixer Grinder', 1, 2499, 'UPI', 'Bangalore');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1006, '2026-02-06', 'C006', 'Neha Verma', 'Beauty', 'Face Cream', 4, 299, 'Credit Card', 'Delhi');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1007, '07-02-2026', 'C007', 'Rahul Das', 'Grocery', 'Cooking Oil 1L', 5, 180, 'Cash', 'Kolkata');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1008, '08-02-2026', 'C008', 'Anjali Nair', 'Fashion', 'Women''s Jeans', 2, 1199, 'UPI', 'Kochi');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1009, '09-02-2026', 'C009', 'Suresh Patel', 'Electronics', 'Smartphone', 1, 15999, 'Debit Card', 'Ahmedabad');
-- INSERT INTO Orders
-- (Order_ID, Order_Date, Customer_ID, Customer_Name, Product_Category, Product_Name, Quantity, Unit_Price, Payment_Mode, Store_Location)
-- VALUES
-- (1010, '10-02-2026', 'C010', 'Meena Iyer', 'Home  Kitchen', 'Pressure Cooker', 1, 1899, 'Credit Card', 'Pune');
 -- SELECT *  from ORDERS;
-- =======================================
-- 1. Convert all customer names to uppercase
-- SELECT UPPER(Customer_Name) AS Customer_Name_Upper FROM Orders;

-- 2. Extract first 5 characters from Product_Name.
-- SELECT SUBSTR(Product_Name, 1, 5) AS First_5_Chars FROM Orders;

-- 3. Find length of each Customer_Name
-- SELECT length(Customer_Name) as length_customer from ORDERS;
-- 4. Replace "Rice" with "Premium Rice" in Product_Name
-- SELECT Replace(Product_Name ,'Rice','Premium Rice' )  AS Updated_Product from ORDERS;
-- 5.Remove leading and trailing spaces from Customer_Name.
-- SELECT TRIM(Customer_Name) AS updated_Name FROM Orders;
-- 6.Concatenate First_Name and Last_Name as Full_Name.

-- SELECT 
-- SUBSTR(Customer_Name, 1, INSTR(Customer_Name, ' ') - 1) || ' ' ||
-- SUBSTR(Customer_Name, INSTR(Customer_Name, ' ') + 1) AS Full_Name
-- FROM Orders;
-- 7. Find customers whose names start with 'A'
-- SELECT Customer_Name FROM Orders WHERE Customer_Name LIKE 'A%';
-- 8. Extract the last 3 digits from Order_ID
-- SELECT Order_ID, SUBSTR(Order_ID, -3) AS Last_3_Digits FROM Orders;
-- 9. Reverse the Product_Name
-- SELECT REVERSE(Product_Name) AS Reversed_Product FROM Orders;
-- 10 .Convert first letter of each word in Product_Name to uppercase
-- SELECT INITCAP(Product_Name) AS Formatted_Product_Name FROM Orders;
-- 11 . Count how many times letter 'a' appears in Customer_Name
-- SELECT Customer_Name,
-- LENGTH(LOWER(Customer_Name)) - LENGTH(REPLACE(LOWER(Customer_Name), 'a', '')) AS Count_Of_A
-- FROM Orders;
-- Find customers whose name contains 'kumar'
-- SELECT Customer_Name FROM ORDERS WHERE LOWER(CUSTOMER_NAME) LIKE '%kumar%';
-- Pad Order_ID with leading zeros to make it 6 digits.
-- SELECT Order_ID, LPAD(Order_ID, 6, '0') AS Padded_Order_ID
-- FROM Orders;

